# Generated by Django 4.2.5 on 2023-09-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasbooking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_details',
        ),
        migrations.DeleteModel(
            name='Client_details',
        ),
    ]
